config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  resources :subreddits, only: [:show, :create, :new, :index, :destroy] do
      resources :posts, only: [:show, :new, :create, :destroy, :update, :edit]

  end
  resources :post, only: [:index, :edit, :destroy, :update] do
      resources :comments, only: [:create, :destroy, :update, :edit]
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  

  resources :sessions

  root to: 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :subreddit
  belongs_to :user
  has_many :comments
end

app/models/subreddit.rb
class Subreddit < ApplicationRecord
    has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :comments
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def logged_in?
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :logged_in?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user_id = session[:user_id]

    if @comment.save
      redirect_to subreddit_post_path(@post.subreddit, @post)
    else
      redirect_to subreddit_post_path(@post.subreddit, @post)
      flash[:notice] = "Comment could not be saved."
    end
  end
  
  def destroy
      @comment = Comment.find(params[:id])
      @post = Post.find(params[:post_id])
      @comment.destroy
      redirect_to @post
  end

  def edit
      @comment = Comment.find(params[:id])
  end

  def update
      @comment = Comment.find(params[:id])
      if @comment.update_attributes(comment_params)
          redirect_to subreddit_post_path(@post.subreddit, @post)
      end
  end
private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
      @posts = Post.all
      @subreddits = Subreddit.all
      @subreddit = Subreddit.new
  end

  def new
      @subreddit = Subreddit.find(params[:subreddit_id])
      @post = Post.new
  end

  def create
      @subreddit = Subreddit.find(params[:subreddit_id])
      @post = @subreddit.posts.new(post_params)
      @post.user_id = session[:user_id]
      if @post.save
          redirect_to @subreddit
      else
          flash[:notice] = "Post could not be saved"
          redirect_to :back
      end
  end

  def show
      @post = Post.find(params[:id])
      @comment = @post.comments.new
  end

  def destroy
      @post = Post.find(params[:id])
      @subreddit = Subreddit.find(params[:subreddit_id])
      @post.destroy
      redirect_to @subreddit
  end

  def edit
      @post = Post.find(params[:id])

  end

  def update
      @post = Post.find(params[:id])
      if @post.update_attributes(post_params)
          redirect_to subreddit_path(@post.subreddit)
      end
  end
private
def post_params
    params.require(:post).permit(:title, :body, :url)
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end

end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  def create
      @subreddit = Subreddit.new(subreddit_params)
      @subreddit.save
      redirect_to @subreddit
  end
  def new
      @subreddit = Subreddit.new
  end
  def index
      @posts = Post.all
      @subreddits = Subreddit.all
      @subreddit = Subreddit.new
  end
  def show
      @subreddit = Subreddit.find(params[:id])
  end
  def destroy
      @subredditIndex = subreddit_post_path
      @subreddit = Subreddit.find(params[:subreddit_id])
      @subreddit.destroy
      redirect_to @subredditIndex

  end
  private
  def subreddit_params
      params.require(:subreddit).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end

    def create
      @user = User.new(allowed_params)
      if @user.save
        redirect_to root_url, notice: 'Thank you for signing up!'
        session[:user_id] = @user.id
      else
        render :new
      end
    end

    private

    def allowed_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subreddits_helper.rb
module SubredditsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <div class="top-bar">
      <div class="top-bar-title">
        <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
          <button class="menu-icon dark" type="button" data-toggle></button>
        </span>
        <strong><%= link_to 'theDRUNKENhand', root_path %></strong>
      </div>
      <div id="responsive-menu">
        <div class="top-bar-left">
          <ul class="dropdown menu" data-dropdown-menu>
            <li>
              <a href="<%= subreddits_path %>">Streamers</a>
              <ul class="menu vertical">
                  <% Subreddit.all.each do |s| %>
                      <li><%= link_to s.title, s %></li>
                  <% end %>
              </ul>
            </li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">Donate</a></li>
          </ul>
        </div>
        <div class="top-bar-right">
          <ul class="menu">
              <div id="user_header">
                <% if logged_in? %>
                   <%= link_to 'Logout', session_path('bogus-id'), method: :delete %>
                <% else %>
                   <%= link_to "Sign Up", signup_path %>
                   <%= link_to "Log In", login_path %>
                <% end %>
              </div>
            <!-- <li><input type="search" placeholder="Search"></li> -->
            <!-- <li><button type="button" class="button">Search</button></li> -->
          </ul>
        </div>
      </div>
    </div>

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="row">
        <%= yield %>
    </div>

  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for([@subreddit, @post], :url => subreddit_post_path, :method => 'patch') do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true %>
    <%= f.label :body %>
    <%= f.text_area :body %>
    <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>Latest Posts</h1>
<div class="post-box">
    <% @posts.reverse.each do |p| %>
        <div class="post-border">
            <p class ="to-the-right">
                <% if session[:user_id] == p.user.id %>
                    <%= link_to "Edit Post", edit_subreddit_post_path(p.subreddit, p) %>
                    <%= link_to "Delete Post", subreddit_post_path(p.subreddit, p), method: :delete %>
                <% end %>
            </p>
            <p class="to-the-right">
                <% if p.updated_at != p.created_at %>
                    Edited: <%= p.updated_at %>
                <% end %>
            </p>
            <p class="to-the-right">
                Discussion: <%= link_to p.subreddit.title, subreddit_path(p.subreddit, p) %>
            </p>
            <div class="post-contents">
                <p> <%= link_to p.title, subreddit_post_path(p.subreddit, p) %> </p>
                <p><%= p.body %></p>
                <%= p.comments.count %> comments
            </div>
            <div class="to-the-right">Created: <%= p.created_at %> by: <%= p.user.email %></div>
        </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<%= form_for([@subreddit, @post]) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true %>
    <%= f.label :body %>
    <%= f.text_area :body %>
    <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<p>
    <p class ="to-the-right right-border">
        <% if session[:user_id] == @post.user.id %>
            <%= link_to "Edit Post", edit_subreddit_post_path(@post.subreddit, @post) %>
            <%= link_to "Delete Post", subreddit_post_path(@post.subreddit, @post), method: :delete %>
        <% end %>
    </p>

        <h1 id="title"> <%= @post.title %> </h1>
        <div class="post-box">
            <div class="to-the-right">Created: <%= @post.created_at %></div>
            <p><%= @post.body %></p>
        </div>

    <p>
    <div class="invisible-border">
        <% if logged_in? %>
                <%= form_for [@post, @comment] do |f| %>
                    <%= f.text_area :body %>
                    <%= f.submit %>
                <% end %>
        <% else %>
            <p>Log in to Create Posts</p>
        <% end %>
    </div>
</p>
    <div class="invisible-border">
        <% @post.comments.reverse.each do |c| %>
            <p>
                <p class ="to-the-right">
                    <% if session[:user_id] == c.user_id && logged_in? %>
                        <%= link_to "Edit Comment", post_comments_path(c.post, c) %>
                        <%= link_to "Delete Comment", post_comments_path(c.post, c), method: :delete %>
                    <% end %>
                </p>
                <%= c.body %>

                <% if @post.comments.count > 0 %>
                <%= pluralize(@post.comments.count, "comment") %>
                    <div class="to-the-right">
                        Created: <%= c.created_at %> by:
                    </div>
                <% else %>
                    <p>No Comments</p>
                <% end %>
            </p>
        <% end %>
    </div>

app/views/subreddits/index.html.erb
<h1 id="title">Streamers</h1>
<% @subreddits.each do |s| %>
    <p class="deck-container"><%= link_to s.title, s %></p>
<% end %>
<div class ="invisible-border"
     <% if logged_in? %>
        <%= form_for(@subreddit) do |f| %>
            <p>Create New Discussion</p>
            <%= f.text_field :title %>
            <%= f.submit %>
        <% end %>
        <% else %>
        <p>Moderator Log in to Create New Discussion</p>
    <% end %>
</div>

app/views/subreddits/new.html.erb
<%= form_for(@subreddit) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit %>
<% end %>

app/views/subreddits/show.html.erb
<p>

        <h1><p id="title"><%= @subreddit.title %></p></h1>
        <% if logged_in? %>
            <p class="to-the-right"><%= link_to "New Post", new_subreddit_post_path(@subreddit) %></p>
        <% end %>

    <div class="post-box">
        <% @subreddit.posts.each do |p| %>
        <div class="post-border">
            <p class ="to-the-right">
                <% if session[:user_id] == p.user.id %>
                    <%= link_to "Edit Post", edit_subreddit_post_path(p.subreddit, p) %>
                    <%= link_to "Delete Post", subreddit_post_path(p.subreddit, p), method: :delete %>
                <% end %>
            </p>
            <p class ="to-the-right">
                <% if p.updated_at != p.created_at %>
                    Edited: <%= p.updated_at %>
                <% end %>
            </p>
            <div class="post-contents">
                <p><%= link_to p.title, subreddit_post_path(p.subreddit, p) %></p>
                <p><%= p.body %></p>
                <%= p.comments.count %> comments
            </div>
            <div class="to-the-right">Created: <%= p.created_at %> by: <%= p.user.email %></div>

        </div>
        <% end %>
    </div>
</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>